### ISSUE TITLE
how to install using zplug

### ISSUE THREAD

**Issue by ninjajs** [eendroroy/alien#11]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x ] support request

Hi, I'm finding the documentation a little confusing.

I installed zplug then I ran: 
zplug "eendroroy/alien"

Now do I need to update this line in .zshrc?
ZSH_THEME="[name of theme]"

**Comment by eendroroy** [comment]
add `zplug "eendroroy/alien"` in your `.zshrc`.

**Comment by ninjajs** [comment]
Is there something else I need to do? I've added this to the top of my .zshrc since installing zplug:
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh
zplug "eendroroy/alien"

but it doesn't have any effect. I'm using ohmyzsh as well.

**Comment by eendroroy** [comment]
Take a look at this: [.zshrc](https://github.com/eendroroy/dotfiles/blob/master/common/zshrc.symlink)

This work for you:
```bash
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "eendroroy/alien"

if ! zplug check --verbose; then
  zplug install
fi
zplug load
```

**Comment by ninjajs** [comment]
Its working now with the code you provided. thanks

**Comment by DollarAkshay** [comment]
I am getting this `/Users/akshaylaradhaya/.oh-my-zsh/oh-my-zsh.sh:source:116: no such file or directory: /Users/akshaylaradhaya/.oh-my-zsh/themes/alien.zsh-theme`
