### ISSUE TITLE
zsh slows down in git reopsitories

### ISSUE THREAD

**Issue by shubhsherl** [eendroroy/alien#13]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
*Bug*
* **What is the current behavior?**
slows down when git repository is too large(like in my case 1.6GB)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
Clone a repo more of size more than a GB. And `cd` and you will get to know the lagging behavior.

* **What is the expected behavior?**
It should not lag.

* **What is the motivation / use case for changing the behavior?**
for better and smooth usage.

* **Please tell us about your environment:**
 - Arch Linux
 - Terminal **kitty**

- Plugin Manager: oh-my-zsh
- ZSH Version: 5.5.1

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc)

**Comment by eendroroy** [comment]
Thanks for creating the issue. It might take some time to troubleshoot and fix it.

**Comment by eendroroy** [comment]
Hi @shubhsherl 
Could test with this repo?
I don't see any lagging due to large repo size.
I am using Alacritty terminal emulator.

**Comment by eendroroy** [comment]
Missed the repo url, sorry.

https://github.com/iboneyard/test_repo

**Comment by shubhsherl** [comment]
@eendroroy Its working fine with the given repo, can you try this one.
`git clone --recursive https://github.com/boostorg/boost.git`

**Comment by eendroroy** [comment]
Now I see the lagging.

**Comment by eendroroy** [comment]
I have made some change. Do you see any improvement now?

**Comment by shubhsherl** [comment]
Yaa, its working fine now, but still I have to wait for some time....but better than before.

**Comment by eendroroy** [comment]
Still trying to make it faster.

**Comment by shubhsherl** [comment]
In the repos, like the source code of Gentoo, it is still lagging.

**Comment by eendroroy** [comment]
Made few upgrades. The lagging should be gone now.

**Comment by shubhsherl** [comment]
@eendroroy thanks, it works like a charm 🎉
