### ISSUE TITLE
Can't type anything when running on zsh at  cygwin

### ISSUE THREAD

**Issue by mike-code** [eendroroy/alien#14]
* **I'm submitting a ...**
  - [x] bug report

* **Do you want to request a *feature* or report a *bug*?**

Report a bug (unless it's not supported)

* **What is the current behavior?**

I can't type anything after the theme is loaded via antigen

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

I open new shell, this what comes up, and believe me, I strike the keyboard but no character appear. The caret is blinking though so the window is reponsive. `ctrl+c` also won't work

![image](https://user-images.githubusercontent.com/2964642/41745754-55c36fba-75a8-11e8-9bfd-45abbc311b9d.png)

* **What is the motivation / use case for changing the behavior?**

I would like to use alien on windows too.

* **Please tell us about your environment:**

- Plugin Manager: antigen, ohmyzsh
- ZSH Version: 5.5-1

Also, cywgin  x64 on Windows 7.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc)

I boiled down .zshrc to those lines only
```
source "$HOME/antigen/antigen.zsh"
export ALIEN_THEME="green"
antigen theme eendroroy/alien alien
antigen apply
```

**Comment by eendroroy** [comment]
Could you please try this one?? https://github.com/eendroroy/alien-win

**Comment by mike-code** [comment]
It works now! The UI looks the same (no coloured arrows) but that's minor thing. 
You think you could do the same to alien-minimal?

**Comment by eendroroy** [comment]
I will also create a port of `alien-minimal` :)

Not sure about why you are facing the color issue. I have no issue with color.
<img width="823" alt="screen shot 2018-06-23 at 2 03 27 am" src="https://user-images.githubusercontent.com/20620104/41796913-f34b1878-7689-11e8-9708-bed9e823e726.png">

**Comment by eendroroy** [comment]
Check it out :)
https://github.com/eendroroy/alien-mintty
