### ISSUE TITLE
history is empty when restarted

### ISSUE THREAD

**Issue by zirosas** [eendroroy/alien#17]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [*] support request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
When restarted the shell, history becomes empty.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
Close the shell and restart again. Check history.

* **What is the expected behavior?**
The history should display, if possible with some options.

* **What is the motivation / use case for changing the behavior?**
history is really important for shell users.

* **Please tell us about your environment:**

- Plugin Manager: [antigen | zplug | oh-my-zsh | ... ]
- ZSH Version

 oh-my-zsh
zsh 5.4.2

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc)
Thanks for the awesome app, I really want to use this if the history is fixed.

**Comment by salmanulfarzy** [comment]
Command history in `Zsh` is handled with `HISTFILE` and AFAIK prompts do not alter it. Does this happen with other prompts for you ?

Make sure your history file is setup properly.

**Comment by eendroroy** [comment]
Is it the first time you switched from `bash` to `zsh`?

**Comment by zirosas** [comment]
I'm not switching from bash to zsh. I've been using zsh with oh-my-zsh.sh.
I've changed .zshrc from source $ZSH/oh-my-zsh.sh to source ~/alien/alien.zsh

**Comment by eendroroy** [comment]
Did you follow OMZ's guide to install theme? https://github.com/robbyrussell/oh-my-zsh/wiki/Customization#overriding-and-adding-themes
