### ISSUE TITLE
Problem with git stash

### ISSUE THREAD

**Issue by stefano-bragaglia** [eendroroy/alien#19]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
I think it is a bug (i.e.: command missing or misspelled).

* **What is the current behavior?**
I just updated to the latest version on `master` and I noticed `@{}` to appear in my prompt.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
I just updated to the latest version on `master` and I noticed `@{}` to appear in my prompt.
I further digged and I figured out that it is possibly related to git stash as I see for a second:
```alien_git_stash:1: command not found: plib_git_stash```

* **What is the expected behavior?**
I'm not sure what I should expected to see because it's first for me, just wanted to let you know.

* **What is the motivation / use case for changing the behavior?**
It wasn't working like this before.

* **Please tell us about your environment:**
  - Plugin Manager: [antigen | zplug | oh-my-zsh | ... ]
  - ZSH Version
  
  I'm on a Mac with Mojave, I'm using Terminal.app with Nerd font on latest oh-my-zsh and zsh 5.4.2.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc)
Notice that having or not having something stashed produces always the same behaviour described above. Adding or removing things from the stash always produces `@{}` as a result.

**Comment by stefano-bragaglia** [comment]
The libraries in `libs` were in a detached status.
I run: `git submodule update --init --recursive` and now everything is fine.
Apologies for having reported it as a bug.
Shall we leave it here in case other people have the same issue?

**Comment by eendroroy** [comment]
No Problem, glad you are using the theme 👍 

Let's keep it for reference.
