### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by betaboon** [eendroroy/alien#23]
Maybe after all the changes lately it would be a good idea to tag a new minor release ?

**Comment by eendroroy** [comment]
Actually trying to solve the issue here:
Git prompt is disappeared in every other render in attached working folder. Also facing slowness.
[alien-demo.zip](https://github.com/eendroroy/alien/files/3014183/alien-demo.zip)
[![asciicast](http://asciinema.org/a/237102.svg)](https://asciinema.org/a/237102)

**Comment by eendroroy** [comment]
Figured it out.
It was a problem with my python installation. Some aliases (that used python scripts) causing the problem.

Now just looking for a way to make a bit faster.

**Comment by betaboon** [comment]
@eendroroy has the git-prompt been faster before my PRs ?

**Comment by eendroroy** [comment]
Not really. There is no noticeable lag after your PRs. It's just that the theme was slower than I expected from beginning for comparatively large repos.
I was hoping to make it bit faster before any new release.

**Comment by betaboon** [comment]
I'm getting these results on a bigger repo.
```
alien_prompt_section_exit 1ms
alien_prompt_section_user 2ms
alien_prompt_section_path 1ms
alien_prompt_section_vcs_branch 8ms
alien_prompt_section_vcs_status 77ms
alien_prompt_section_vcs_dirty 139ms
alien_prompt_section_newline 0ms
alien_prompt_section_venv 2ms
alien_prompt_section_ssh 1ms
alien_prompt_section_prompt 1ms
```

so as an indicator the vcs_status and vcs_dirty are especially slow.

### How I got those numbers
adding the following line directly above the call of `$__section_function` in `modules/prompt.zsh`
```
TIMEFMT="$__section_function %mE"; { time ($__section_function);} 2>>/tmp/alien.log
```

**Comment by eendroroy** [comment]
Probably the issue needs to fixed in the core repo: `promptlib-zsh`

**Comment by eendroroy** [comment]
BTW, I created a new release 2.0.0
