### ISSUE TITLE
User-defined components

### ISSUE THREAD

**Issue by ryanrhee** [eendroroy/alien#28]
Is there a way to add user-defined components?

**Comment by eendroroy** [comment]
Currently there is no option for that.

**Comment by betaboon** [comment]
@ryanrhee the easiest way right now is to add a section like this:
https://github.com/eendroroy/alien/blob/master/modules/sections.zsh#L6

you can then refer to a section in your config by the text after the last `_`.
eg. define a section called `alien_prompt_section_foobar` then use it in your config as `foobar`

**Comment by eendroroy** [comment]
> @ryanrhee the easiest way right now is to add a section like this:
> https://github.com/eendroroy/alien/blob/master/modules/sections.zsh#L6
> 
> you can then refer to a section in your config by the text after the last `_`.
> eg. define a section called `alien_prompt_section_foobar` then use it in your config as `foobar`

That is modifying the theme itself, right?

**Comment by betaboon** [comment]
@ryanrhee @eendroroy 
i guess it would also be possible to define a file (eg. `my-alien-sections.zsh`)
and then source it before sourcing alien (with your zsh-plugin-manager eg `antibody`).

that seems to work as well

**Comment by eendroroy** [comment]
May be we can create a configuration option for `ALIEN_CUSTOM_SECTIONS_PATH`
like `ALIEN_CUSTOM_THEME_PATH`:

```bash
export ALIEN_CUSTOM_SECTIONS_PATH=/path/to/custom/sections
```
It will source all `zsh` files from `/path/to/custom/sections`

**Comment by ryanrhee** [comment]
Could also check a path by default? something like `${HOME}/.alien/custom/sections`

**Comment by betaboon** [comment]
i dislike the idea of checking a path by default.

**Comment by betaboon** [comment]
@ryanrhee is your request solved by the provided information ?

**Comment by ryanrhee** [comment]
I'll try defining a custom section and using it my config.

will the `alien_prompt_section_` prefix ever change?

**Comment by betaboon** [comment]
@ryanrhee i currently do not see any reason for the prefix changing. though it can obviously not be ruled out ;)

can this issue be closed ?

**Comment by ryanrhee** [comment]
yup, it can be closed.
