### ISSUE TITLE
Two line promt

### ISSUE THREAD

**Issue by harvestnide** [eendroroy/alien#29]
Feature request/Question.
Hi. Really enjoying this theme, but two line promt isn't perfect for me in some cases, is there any way to change it?

**Comment by betaboon** [comment]
@harvestnide as can be seen [here](https://github.com/eendroroy/alien#sections) you can just define the sections you want and just not use `newline` ;)

**Comment by harvestnide** [comment]
wow. I literally edit those settings more than once, but never seen it before. Thx a lot

**Comment by betaboon** [comment]
@harvestnide you're welcome. enjoy :)
