### ISSUE TITLE
Changes to ALIEN_* variables don't take effect

### ISSUE THREAD

**Issue by alextremblay** [eendroroy/alien#30]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
First off, thank you for creating this ZSH theme. It's absolutely fantastic

The bug I'd like to report is an inability to change any of the variables (ex. `ALIEN_SECTIONS_LEFT_SEP_SYM` or `ALIEN_USE_NERD_FONT` after the theme has been sourced.

* **What is the current behavior?**
any `ALIEN_` vars exported before the theme is first sourced work as expected.
any `ALIEN_` env vars modified and re-exported after the theme is first sourced take no effect, even if you source the theme again.

Well, to be more specific, it seems like they DO take effect momentarily, but some async process comes in and overwrites them with the original values from when the theme was initially sourced. Please see the included asciinema recording below for an example of this behavour

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
This recording is a minimal example of the problem
https://asciinema.org/a/ebS4Z9Tkd3Y292WtGITBZS28C

* **What is the expected behavior?**
I expect changes to env vars to take effect as they do in the asciinema recording fro mthe README

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Terminal emulator: iterm2 3.3.8
- Plugin Manager: none
- ZSH Version: 5.7.1
- Operating System: MacOS 10.14

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc)

**Comment by eendroroy** [comment]
It will only work if you put it in `.zshrc` and open a new terminal.

Asciinema recording was created only to show some of the settings options (with some tweaks to the original theme so that the changes in variables takes effect immediately). The original theme will not work like that.

**Comment by alextremblay** [comment]
Ahhhh. I see.

Thank you
