### ISSUE TITLE
stderr disappears (again)

### ISSUE THREAD

**Issue by zcutlip** [eendroroy/alien#33]
Looks like issue #32 is still happening. Worked fine for a few days, but stderr has disappeared on me in one of my terminal sessions.

**Comment by zcutlip** [comment]
I've uncommented lines in async.zsh as described here:
https://github.com/eendroroy/alien/issues/32#issuecomment-578031239

I'll update if that does/doesn't help.

**Comment by eendroroy** [comment]
Could you please share your configuration?

**Comment by zcutlip** [comment]
Sure:

```
export ALIEN_SECTIONS_LEFT=(
  exit
  user
  path
  vcs_branch:async
  vcs_status:async
  vcs_dirty:async
  versions:async
  newline
  ssh
  venv
  prompt
)
export ALIEN_SECTIONS_RIGHT=(
  time
  battery
)

export ALIEN_SECTION_PATH_COMPONENTS=3
export ALIEN_THEME="red"
```

**Comment by eendroroy** [comment]
Continues on #32
