### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by zxp1314gch** [eendroroy/alien#34]
<img width="857" alt="截屏2020-06-16上午9 38 13" src="https://user-images.githubusercontent.com/56782560/84722196-1be2a100-afb5-11ea-9ce2-c6d50b36087a.png">

**Comment by zxp1314gch** [comment]
export ALIEN_SECTIONS_LEFT_SEP_SYM=
export ALIEN_SECTIONS_RIGHT_SEP_SYM=
export ALIEN_PROMPT_SYM=
three '?'

**Comment by betaboon** [comment]
could you please properly describe your issue?
