### ISSUE TITLE
Please clarify the adding of Alien theme on Oh-My-Zsh in Readme.md

### ISSUE THREAD

**Issue by sidambhire** [eendroroy/alien#37]
**Problem description**
In the readme.md file, there's nothing below the Oh-My-Zsh section. Are we required to clone the full repository as mentioned below it in manually cloning?

**Possible solution**
Can you show how it is done for Oh-My-Zsh, like you have shown for other plugin managers? The Oh-My-Zsh link you have provided is also confusing.

**Comment by eendroroy** [comment]
Could you please try the official guide:

https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#overriding-and-adding-themes

Please let me know if it works for you.
