### ISSUE TITLE
UTF issue ?

### ISSUE THREAD

**Issue by RSickenberg** [eendroroy/alien#5]
![screen shot 2017-06-20 at 14 29 51](https://user-images.githubusercontent.com/16922548/27333094-f8a05d92-55c4-11e7-87cd-996b64a24bca.png)

**Comment by eendroroy** [comment]
See here: [Issue 1](https://github.com/eendroroy/alien/issues/1)

**Comment by mqliutie** [comment]
Hello, I have chosen a font but it still not show the icon

**Comment by eendroroy** [comment]
You can try installing one from here [Meslo powerline fonts](https://github.com/powerline/fonts/tree/master/Meslo%20Dotted).

**Comment by cevaris** [comment]
Reviving this old thread.

<img width="260" alt="Screenshot 2023-03-22 at 12 00 35 PM" src="https://user-images.githubusercontent.com/4671809/226996924-08b75233-3ff5-4670-b8a2-bc111a9a9486.png">

I have installed alien prompt on Mac OS X 13.2.1 (Ventura), including the Meslo powerline fonts but my prompt is still failing to render icons. 

<img width="395" alt="Screenshot 2023-03-22 at 12 01 09 PM" src="https://user-images.githubusercontent.com/4671809/226996880-c65b06e2-c8e1-4e8d-b613-9dd0aa60dc07.png">


I also tried the export `ALIEN_USE_NERD_FONT=1` font config with no luck. 

Do I have to somehow point alien to the Meslo fonts?

**Comment by cevaris** [comment]
Actually, looking at the source font symbols, they seem broken. even when viewing on web.
I will just try overrriding the symbols via ENV variables. 

![Screenshot 2023-03-22 at 20 23 47](https://user-images.githubusercontent.com/4671809/227084009-fbc2ad67-e0dc-4b8e-8043-86801027a5d7.png)

**Comment by eendroroy** [comment]
You can try `font-hack-nerd-font`

<img width="936" alt="Screenshot 2023-03-27 at 11 39 46 AM" src="https://user-images.githubusercontent.com/20620104/227850301-7e2fc9bf-a326-475f-8177-7bc7b89ca4ca.png">

**Comment by cevaris** [comment]
@eendroroy thanks for the suggestion. I attempted installing that package with no luck..

I have `font-hack-nerd-font` installed. 

<img width="641" alt="Screenshot 2023-03-27 at 2 40 33 PM" src="https://user-images.githubusercontent.com/4671809/228061532-815af779-b452-44d4-a12e-a81210e2e2ac.png">

I have `ALIEN_USE_NERD_FONT` enabled.
<img width="642" alt="Screenshot 2023-03-27 at 2 40 46 PM" src="https://user-images.githubusercontent.com/4671809/228061565-86aa090e-010a-4021-a2bd-f3f514fd36b7.png">

But i dont have any symbols rendered...

Here is my config

```
export ALIEN_USE_NERD_FONT=1
export ALIEN_THEME="soft"
export ALIEN_SECTION_TIME_FORMAT=%H:%M:%S
export ALIEN_SECTIONS_LEFT=(
  exit
  time
  user
  path
  vcs_branch:async
  # vcs_status:async
  # vcs_dirty:async
  newline
  # ssh
  # venv
  prompt
)
source ~/src/zsh-alien/alien.zsh
```

**Comment by eendroroy** [comment]
Can you please try selecting the font in iTerm profile settings?

<img width="940" alt="Screenshot 2023-03-30 at 2 15 35 PM" src="https://user-images.githubusercontent.com/20620104/228773511-ab74713e-e694-448f-81be-f4a3badca1f5.png">

**Comment by cevaris** [comment]
That fixed it!
<img width="588" alt="Screenshot 2023-03-30 at 1 17 34 PM" src="https://user-images.githubusercontent.com/4671809/228941138-95e0d31a-9301-40e3-9f08-35208394cb9b.png">


Works in VS Code terminal too. 
<img width="702" alt="Screenshot 2023-03-30 at 1 17 10 PM" src="https://user-images.githubusercontent.com/4671809/228941187-a7ea2664-f70c-4cac-a154-15ce9a80e8a8.png">

<img width="659" alt="Screenshot 2023-03-30 at 1 17 18 PM" src="https://user-images.githubusercontent.com/4671809/228941182-1b014558-5977-43aa-82e6-2c6246ca6cee.png">


**Thanks!**

**Comment by eendroroy** [comment]
Welcome :)
