### ISSUE TITLE
async scripts not found

### ISSUE THREAD

**Issue by paanvaannd** [eendroroy/alien#6]
I cloned the repo to my `.oh-my-zsh/custom/themes` directory as directed and modified `.zshrc` to specify `ZSH_THEME="alien/alien"` and set `ALIEN_THEME="red"`.

The theme seems to be working, at least visually, but I keep getting the following error upon starting a Terminal instance:

>/home/USER/.oh-my-zsh/custom/themes/alien/alien.zsh-theme:source:5: no such file or directory: /home/USER/.oh-my-zsh/custom/themes/alien/libs/promptlib/activate
>/home/USER/.oh-my-zsh/custom/themes/alien/alien.zsh-theme:source:6: no such file or directory: /home/USER/.oh-my-zsh/custom/themes/alien/libs/zsh-async/async.zsh
>/home/USER/.oh-my-zsh/custom/themes/alien/alien.zsh-theme:source:7: no such file or directory: /home/USER/.oh-my-zsh/custom/themes/alien/libs/zsh-256color/zsh-256color.plugin.zsh
>alien_async_prompt:1: command not found: async_init                             
>alien_async_prompt:2: command not found: async_start_worker
>alien_async_prompt:3: command not found: async_register_callback
>alien_async_prompt:4: command not found: async_job
>alien_venv:1: command not found: plib_venv`

and the following lines echoed to stdout every time I run a command:

>alien_async_prompt:1: command not found: async_init                             
>alien_async_prompt:2: command not found: async_start_worker
>alien_async_prompt:3: command not found: async_register_callback
>alien_async_prompt:4: command not found: async_job
>alien_venv:1: command not found: plib_venv`

e: Indeed, the links to other git repos (such as zsh-async) are empty in my directory list. I will try deleting those and manually cloning those repos to the required directory soon and see if that helps.

**Comment by paanvaannd** [comment]
Root issue: links to dependency git repos were not populated through `git clone` of this repo.
Solution:
1. delete folders within `~/.oh-my-zsh/custom/themes/alien/libs`
2. clone original dependency repos to this directory instead
3. rename the `promptlib` repo, which is cloned as `promptib-zsh` initially, is renamed to `promptlib` (or changing the code within `alien.zsh` to resolve the name conflict
4. restart terminal emulator session

**Comment by paanvaannd** [comment]
Root issue: links to dependency git repos were not populated through `git clone` of this repo.
Solution:
1. delete folders within `~/.oh-my-zsh/custom/themes/alien/libs`
2. clone original dependency repos to this directory instead
3. rename the `promptlib` repo, which is cloned as `promptib-zsh` initially, is renamed to `promptlib` (or changing the code within `alien.zsh` to resolve the name conflict
4. restart terminal emulator session

**Comment by eendroroy** [comment]
I would have suggest the following approach:

1. `git clone https://github.com/eendroroy/alien.git`
1. `cd alien`
1. `git submodule update --init --recursive`

**Comment by TactaiNemo** [comment]
@eendroroy , your solution doesn't work for me. Did you miss anything?

**Comment by eendroroy** [comment]
Whats inside `alien/libs` folder? Can you show the directory tree?

**Comment by TactaiNemo** [comment]
@eendroroy , thank you for reply.

My directory tree is like this:

~/IDE/zsh....
then 
~/IDE/alien:
LICENSE           alien.plugin.zsh  libs
README.md         alien.zsh         modules
alien.applescript alien.zsh-theme   screenshots

**Comment by eendroroy** [comment]
Whats inside libs folder?

**Comment by eendroroy** [comment]
Also please share about your environment.

**Comment by TactaiNemo** [comment]
My libs/

promptlib    zsh-256color zsh-async

I am using Mac.

**Comment by TactaiNemo** [comment]
@eendroroy ,you know what, please stop spending more time on this issue. I'll go through a detailed setup tutorial on youtube. thanks man.
