### ISSUE TITLE
Black prompt background and text color though ALIEN_THEME value is set

### ISSUE THREAD

**Issue by paanvaannd** [eendroroy/alien#7]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **What is the current behavior?**

Though Alien is working fine on Ubuntu, both the prompt background and text are colored black though I have set `ALIEN_THEME=blue` in .zshrc.

* **What is the expected behavior?**

Alien's prompt is colored as it should be.

* **Please tell us about your environment:**

Plugin Manager: oh-my-zsh
ZSH Version: zsh 5.4.2 (x86_64-apple-darwin6.7.0)
Terminal emulator: iTerm2 v3.1.5
Report Terminal Type (an iTerm2 preference): xterm-256color

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc)

This behavior is experienced in both Terminal and iTerm2.

In iTerm2, going to the current profile's color settings and changing the ANSI color values for normal black changes the background and text color of the prompt and changing the value for bright black changes the color of the indicator on the line where I enter commands. The prompt text is set to the same value as the prompt background and changes with it, so the text is never visible unless highlighted.

Regardless of changing `ALIEN_THEME`'s value, I end up with the same mix of a black prompt background and text. Everything else seems to be working just fine.

I am quite certain I installed Alien properly on my Mac just as I have on Ubuntu (no issues in Ubuntu) through the following method:

* download and install Powerline fonts
* set terminal profile used with alien theme to use Powerline-patched font
* `cd` to .oh-my-zsh/custom/themes
* download alien theme git repo
* `cd alien`
* `git submodule update --init --recursive`
* edit .zshrc to include:

```
# Same results regardless of whether green, blue, or red theme is used
export ALIEN_THEME=blue
ZSH_THEME="alien/alien"
```

* `source ~/.zshrc`

My .zshrc file is as follows:

```
# Executables PATH declaration
export PATH=$HOME/bin:/usr/local/bin:$HOME/Documents/Scripts:$HOME/.local/bin:$HOME/go/bin:$PATH
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
# Declaring default editor through the EDITOR environment variable
export EDITOR=nvim
# Start cowthink + fortune at session login
if [[ $OSTYPE == "linux-gnu" ]]; then
	if [ -x /usr/games/cowsay -a -x /usr/games/fortune ]; then
		fortune -se fortunes literature love riddles science magic translate-me | cowsay -f stegosaurus
	fi
elif [[ $OSTYPE == "darwin"* ]]; then
	if [ -x /usr/local/bin/cowsay -a -x /usr/local/bin/fortune ]; then
		fortune -se fortunes literature love riddles science magic translate-me | cowsay -f stegosaurus
	fi
fi

# LS_COLORS setup
export CLICOLOR=1
LS_COLORS='*.html=34:*.css=36:*.js=33:*.md=32:*.pdf=31:*.zip=44'
export LS_COLORS

# Preferred themes: alien (custom), bira, bureau, funky, minimal, powerlevel9k (custom), robbyrussel, ys
export ALIEN_THEME="blue"
ZSH_THEME="alien/alien"

# Enable command auto-correction.
ENABLE_CORRECTION="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# (plugins can be found in $ZSH/plugins/*)
# Add custom plugins to $ZSH/custom/plugins/
plugins=(brew colorized-man-pages colorize command-not-found copydir copyfile extract git lol nyan sudo web-search zsh-syntax-highlighting)

# Enable fuzzy auto-completion in ZSH
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Sourcing ZSH config file
source $ZSH/oh-my-zsh.sh

# Sourcing ZSH syntax highlighting
if [[ $OSTYPE == "linux-gnu" ]]; then
	source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
elif [[ $OSTYPE == "darwin"* ]]; then
	source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

# For a full list of active aliases, run `alias`.
alias sz="source $HOME/.zshrc"
alias vz="nvim $HOME/.zshrc"
alias t="todo.sh"
alias pomo="gone"

if [[ $OSTYPE == "linux-gnu" ]]; then
	alias open="xdg-open"
	alias notes='~/Documents/Scripts/standard-notes-2.0.3-x86_64.AppImage'
elif [[ $OSTYPE == "darwin"* ]]; then
	alias netinfo="/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I"
	alias ports="netstat -atp tcp"
	alias word="wordgrinder"
fi

```

**Comment by eendroroy** [comment]
@paanvaannd Should be fixed now. Please let me know the result after updating the theme :)

**Comment by paanvaannd** [comment]
Works perfectly, now! Thanks for the help :+)
