### ISSUE TITLE
Install document is demanded

### ISSUE THREAD

**Issue by shengyang998** [eendroroy/alien#8]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

Hi, thanks for the very great work. 
However, I am new to zsh and its themes and plugins. Therefore, I don't quiet understand how to install and configure the alien theme with the content on the README file. Hoping someone can help and add a related link or write a short tutorial to install and configure it. 

----
At first, I followed the README file to try to manually install the theme. Overriding and adding theme is succeed and it is also succeed running the `git submodule update  --init --recursive`, but after that, when I change `ZSH_THEME="alien"` and do `source ~/.zshrc`, it just happened to fail to load the theme. 
Then I tried the antigen method. After installing antigen with `brew install antigen`, I run `antigen theme eendroroy/alien alien` as told, and it seems that it worked. However, it didn't work since I put `antigen theme eendroroy/alien alien` in `~/.zshrc`. 
When I start a new terminal window, I just show `Antigen: Another process in running. `. After running `antigen reset` and start a new window again, the `Antigen: Another process in running.` didn't show up, neither the theme changed. 
Hoping more document provided, I may help after I know the way through.

**Comment by eendroroy** [comment]
The issue - **`Antigen: Another process in running.`** - seems like a bug of `antigen` itself. See the discussion here: https://github.com/zsh-users/antigen/issues/543

I no longer use `antigen`. My current plugin manager is `zplug`. Back when I used `antigen`, this was in my [`.zshrc`](https://github.com/eendroroy/dotfiles/blob/e3aeaed010c7599b0d411a86413717b2885e7f23/common/zshrc.symlink)
```bash
if [ -d ~/.antigen ]; then
  source ~/.antigen/antigen.zsh
fi

# THEMES
antigen theme eendroroy/alien alien

antigen apply
```

And this was the script I used for installing `antigen` https://github.com/eendroroy/dotfiles/blob/master/common/recipes/antigen.sh

**Comment by shengyang998** [comment]
Thank you! It worked. I missed `antigen apply` at the end of the script. 
But using antigen seems too slow when I start a new terminal, maybe I'll try zplug later. 
Thanks a lot @eendroroy

**Comment by eendroroy** [comment]
You are welcome :)
