### ISSUE TITLE
All symbols remain ?s 

### ISSUE THREAD

**Issue by Aponcher** [eendroroy/alien#9]
* **I'm submitting a ...**
  - [X ] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
After installing everything using zplug and npm all my symbols remain ?s in boxes 

* **What is the expected behavior?**

arrows and dirty symbols etc from powerline and or Nerd-font

* **What is the motivation / use case for changing the behavior?**

so the theme actually looks like it should

* **Please tell us about your environment:**

- Plugin Manager: zplug & oh-my-zsh
- ZSH Version

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc)
PS: how might i go about altering the prompt to get rid of certain portions

**Comment by salmanulfarzy** [comment]
[Powerline](https://github.com/powerline/fonts) font is [required](https://github.com/eendroroy/alien#requirements), Do you have it installed and activated ?

> how might i go about altering the prompt to get rid of certain portions

Looks like `PROMPT` and `RPROMPT` are hard coded. You could modify that in your `.zshrc` file

https://github.com/eendroroy/alien/blob/de7189ffb6b9e2663c1a585588d5c4de7f9f1c81/alien.zsh#L24-L34

Note that VCS sections are invoked separately

https://github.com/eendroroy/alien/blob/de7189ffb6b9e2663c1a585588d5c4de7f9f1c81/modules/async.zsh#L5-L25

**Comment by eendroroy** [comment]
Agree with @salmanulfarzy 

Yes, you need to install [Powerline](https://github.com/powerline/fonts) fonts.

And, if you want to change the prompt, you will have to change a few files:
- alien.zsh
- modules/async.zsh
